# Lắng nghe mọi IP
bind 0.0.0.0

# Chạy trên port mặc định
port 6379

# Đặt giới hạn bộ nhớ tối đa là 128MB
maxmemory 128mb

# Chính sách xử lý khi đầy bộ nhớ (xóa các key ít dùng nhất)
maxmemory-policy allkeys-lru

# Cấu hình lưu trữ dữ liệu định kỳ xuống ổ cứng (RDB)
save 900 1
save 300 10
save 60 10000
